version: '3'
services:
  bot:
    container_name: caladbolg
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - './src:/home/node/src'
    command: npm run start:dev
    ports:
    - 3000:3000
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - 27017:27017
