---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "caladbolg-service"
  namespace: "default"
  labels:
    app: "caladbolg"
spec:
  ports:
    - protocol: "TCP"
      port: 80
  selector:
    app: "caladbolg"
  type: "LoadBalancer"
  loadBalancerIP: ""
